name: Update Documentation

on:
  push:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: fwal/setup-swift@v2
    - uses: fwcd/swift-docc-action@v1
      with:
        target: PriorityHeapModule
        output: docs
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
        hosting-base-path: swift-priority-heap
    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs
    - uses: actions/deploy-pages@v4
